language: perl
perl:
  - "5.14"
  - "5.12"
install: "perl ./TEST.PL"
env:
  - PERL_ZMQ_TEST_TARGET=ZMQ-Constants
  - PERL_ZMQ_TEST_TARGET=ZMQ-LibZMQ2
  - PERL_ZMQ_TEST_TARGET=ZMQ-LibZMQ2 PRE_INSTALL=AnyEvent,Proc::Guard
  - PERL_ZMQ_TEST_TARGET=ZMQ-LibZMQ3
  - PERL_ZMQ_TEST_TARGET=ZMQ-LibZMQ3 PRE_INSTALL=AnyEvent,Proc::Guard
  - PERL_ZMQ_TEST_TARGET=ZMQ
